CREATE DATABASE IF NOT EXISTS todo;
USE todo;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  userId VARCHAR(255) NOT NULL
);

ALTER TABLE tasks ADD COLUMN complete BOOLEAN;
-- DROP TABLE tasks;